apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webapi-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: \"false\"
spec:
  rules:
  - http:
      paths:
      - path: /weatherforecast
        backend:
          serviceName: realworld
          servicePort: 5001
